#%RAML 1.0
title: Accounts SFDC System API
version: v1
description: This API is responsilble to connect with Salesforce and perform CRUD operations.
mediaType: application/json

documentation:
  - !include documentation/overview.raml
  - !include documentation/authentication.raml

uses:
  coreLib: /exchange_modules/2e05ecc9-d5ac-469b-9f73-a9279cdf16be/lm-acme-common-raml-fragements/1.0.0/common-raml-fragments.raml
  accountCDMLib: /exchange_modules/2e05ecc9-d5ac-469b-9f73-a9279cdf16be/lm-acme-account-cdm/1.0.0/acme-account-cdm.raml

/accounts:
  securedBy:
    - coreLib.token
  post:
    displayName: enter data
    is: [coreLib.trackable, coreLib.clientIdRequired]
    description: Create new account in Salesforce
    body:
      application/json:
        type: accountCDMLib.accountType
        properties:
          name: 
            required: true
          email:
            required: true
        example: !include /examples/createAccountRequest.raml
    responses:
      201:
        description: 201 response
        headers:
          Content-Type:
            description: content-type
        body:
          type: coreLib.postSuccess
          example: !include /examples/createAccountSuccessResponse.raml
  /{accountid}:
    securedBy:
      - coreLib.token
    uriParameters:
      accountid:
        type: string
        displayName: Account ID
        description: Account Id to be retrived, updated or deleted.
        example: 0019000000DmehK
    get:
      description: Retrieve an account object from Salesforce
      displayName: Retrieve
      is: [coreLib.trackable, coreLib.clientIdRequired]
      responses:
        200:
          description: 200 Response
          headers:
            Content-Type:
              description: content-type
          body:
            application/json:
              type: accountCDMLib.accountType
              example: !include /examples/retrieveAccountResponse.raml
    put:
      description: Updates an account object in Salesforce
      displayName: Update Data
      is: [coreLib.trackable, coreLib.clientIdRequired]
      body:
        application/json:
          type: accountCDMLib.accountType
          example: !include /examples/updateAccountRequest.raml
      responses:
        200:
          description: 200 Response
          headers:
            Content-Type:
              description: content-type
          body:
            type: coreLib.postSuccess
            example: !include /examples/updateAccountSuccessResponse.raml
    delete:
      description: Deletes an account object from Salesforce
      displayName: Deletes 
      is: [coreLib.trackable, coreLib.clientIdRequired]
      responses:
        200:
          description: 200 Response
          headers:
            Content-Type:
              description: string
          body:
            type: coreLib.postSuccess
            example: !include /examples/deleteAccountSuccessResponse.raml